### ISSUE TITLE
Classify messages without mentions

### ISSUE THREAD

**Issue by arkencl** [arkencl/aura#57]
Currently Aura only supports keyword based regex matching and filtering out mentions. It would be interesting to see how much a NLP Pipeline / Module would allow Aura to use normal discord messages to discern further messages for karma gain. I think just NLP wouldn't be enough though, this would require to put members in a relation with other members and messages in a sort of Document Term Matrix and funnelling words into certain categories for further confidence to give karma to the correct persons.

Interesting Library:
https://github.com/huggingface/transformers

**Comment by arkencl** [comment]
related issue: https://github.com/the-programmers-hangout/aura/issues/1

**Comment by arkencl** [comment]
I think it's too complex, even though i kind of wanted to do something like that:

1) The last message before the thanks doesn't have to be of the one who helped person a. Often there are several conversations going on at the same time.
This alone actually disqualifies this of being reasonable, you could maybe give passive karma to everyone but that's kinda meh.
2) It doesn't take into account other helpers.
3) If the message contains a name you have to match or approximate the nearest match to assign the thanks. Another inaccuracy.

**Comment by ineshbose** [comment]
Would Aura be able to follow-up a 'thank you' message that has flaws/inconsistencies like no name or approx match?

Example:
```
Person1: Thanks!
Aura: @<Person1> would you like to thank using Karma? Please mention the user.
Person1: @<Person2>
```
